HW 2
Johanlib/programming_sem1 pull request #2
Opened 2022-09-23 12:10 UTC by Johanlib

2022-10-19 00:31 UTC, Lozov-Petr requested changes

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Exponentiation.c
> +        printf("Binary search: ");
Поиск? Вроде же о степень речь идет...

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +int iteratFibonacci(int number)
```suggestion
int iterativeFibonacci(int number)
```
Такие сокращения не приветствуются

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +    return firstNumber;
Зачем делать последнюю итерацию, если вычисленный `secondNumber` не нужен?

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +    int secondNumber = 1;
```suggestion
    int previousNumber = 0;
    int currentNumber = 1;
```
Так названия отражают "смысл" переменных.

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +int recursFibonacci(int number)
```suggestion
int recursiveFibonacci(int number)
```

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +        flagNumber = true;
```suggestion
        isIncorrectInput = true;
```
Опять же неговорящее имя

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +int iteratFibonacci(int number)
Отрицательные числа? Или лучше unsigned int.

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/Fibonacci.c
> +int recursFibonacci(int number)
Отрицательные числа? Или лучше unsigned int.

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +void bubbleSort(int array[], int lengthArray)
По идее сортировка пузырьком работает за `(len - 1) * len / 2`.
А у тебя за `len * (len - 1)`.

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +        for (int j = 0; j < lengthArray - 1; ++j)
Где-то здесь проблема со временем работы

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +    int temp = 0;
Неговорящее название

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +    int *arrayAux = calloc(maximumElement - minimumElement + 1, sizeof(int));
`maximumElement - minimumElement + 1` используется дважды. Причем во второй раз в цикле. Нужно предварительно вычислить один раз.

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +        flagInput = true;
Имя неговорящее

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +    printf("Enter a array:\n");
```suggestion
    printf("Enter an array:\n");
```

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/bubbleAndCounting.c
> +        flagInputChar = true;
```suggestion
        isCorrectInput = true;
```

2022-10-19 00:31 UTC, Lozov-Petr commented on HWs/HW2/partition.c
> +void partition(int array[], int index, int rigthElement)
Странные имена переменных. Ожидается скорее `leftIndex` и `rightIndex`

2022-10-21 14:48 UTC, Johanlib commented on HWs/HW2/Fibonacci.c
> +    return firstNumber;
Не особо понял вопроса, firstNumber тоже меняется, а выводим мы firstNumber (делаем на одну итерацию больше) для того, чтобы без проблем выводить нулевой элемент как 0.

2023-01-30 23:40 UTC, merged